{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-core/0.2.28/toolkit-core-0.2.28.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-core",
    "version": "0.2.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-release.aar",
          "url": "toolkit-core-android-0.2.28.aar",
          "size": 92771,
          "sha512": "ae4da388b50f662e6a28ba1f98d23ef96b521fbdc3afed54e28b7d755cfb4eb5609faf8879f6acf91c96733700c197efcc8e35d72fa0c283c05cbda3e040104a",
          "sha256": "98e1bb4a938ad4cf7620ff787ee3ace4c05146fd34b0c01896d6fbcadb036f2b",
          "sha1": "e1232314624285a0281e0e1aea8e15d4cbfe2881",
          "md5": "8a175c3ee9ccf944d8b5a96055397b55"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "toolkit-core-release.aar",
          "url": "toolkit-core-android-0.2.28.aar",
          "size": 92771,
          "sha512": "ae4da388b50f662e6a28ba1f98d23ef96b521fbdc3afed54e28b7d755cfb4eb5609faf8879f6acf91c96733700c197efcc8e35d72fa0c283c05cbda3e040104a",
          "sha256": "98e1bb4a938ad4cf7620ff787ee3ace4c05146fd34b0c01896d6fbcadb036f2b",
          "sha1": "e1232314624285a0281e0e1aea8e15d4cbfe2881",
          "md5": "8a175c3ee9ccf944d8b5a96055397b55"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "toolkit-core-android-0.2.28-sources.jar",
          "url": "toolkit-core-android-0.2.28-sources.jar",
          "size": 40943,
          "sha512": "a58b0c258e0248ff7b912cd7250cd891a163034b541285ba2756ee7c47705b643bd4318dd925461902780c9af80054762c153d72e4f6f48467e177a33bbcd5d1",
          "sha256": "a42b5b2582cc1703c3503343f755af47e3d8107921cffbe9ac66ab9963ebc92a",
          "sha1": "09cbdcc822404f6e619611fd95f0584747a74fd6",
          "md5": "873be5bfaa239c9a77e72bb7b01f70e3"
        }
      ]
    }
  ]
}
