{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-web/0.2.21/toolkit-web-0.2.21.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-web",
    "version": "0.2.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.2.21.klib",
          "url": "toolkit-web-js-0.2.21.klib",
          "size": 726764,
          "sha512": "84c90404b9f34eafdf983e7f82f5b50e7230c9b5bd17d873bc8b9decf8630fb71f957768ad54fe411fc8ad8977562c1139e97454d5a5c97ee1130e1f5765da98",
          "sha256": "bcdfd6560c80f920827756239189a5e70442ba50c2c5bd1fc14d913e4d16560f",
          "sha1": "b7971c801fdb37209b2dc0b6db34c1cddf935f70",
          "md5": "83e4dc76812ffb47be71b245fc2786ae"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.2.21.klib",
          "url": "toolkit-web-js-0.2.21.klib",
          "size": 726764,
          "sha512": "84c90404b9f34eafdf983e7f82f5b50e7230c9b5bd17d873bc8b9decf8630fb71f957768ad54fe411fc8ad8977562c1139e97454d5a5c97ee1130e1f5765da98",
          "sha256": "bcdfd6560c80f920827756239189a5e70442ba50c2c5bd1fc14d913e4d16560f",
          "sha1": "b7971c801fdb37209b2dc0b6db34c1cddf935f70",
          "md5": "83e4dc76812ffb47be71b245fc2786ae"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "toolkit-web-js-0.2.21-sources.jar",
          "url": "toolkit-web-js-0.2.21-sources.jar",
          "size": 310481,
          "sha512": "6ffad45ef2ddf28869afe6d84650f52027278081780ce063eb7cf250cdb2c91cb9e88340bb23e1b0842d5582e46aff9cb089d7c57033f7711694e7a29c962e19",
          "sha256": "aef68ba0574c7fc719502a1be4c0b0fd807a588ce44a8b53a0707b54b40c08f0",
          "sha1": "1359493ae835e5e4dd8af30ce07cd46f6a07b30c",
          "md5": "ec169ce4d73afe9da758a5528d76c7b1"
        }
      ]
    }
  ]
}
