{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-web/0.2.14/toolkit-web-0.2.14.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-web",
    "version": "0.2.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.14"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.2.14.klib",
          "url": "toolkit-web-js-0.2.14.klib",
          "size": 714746,
          "sha512": "db0aba566054dd90cef251544793c9d109e6fe37893099559cda22b6588fc39991a440ef43482bd121a260e27de3975d0fc67f63b0b049fb2a22e64962436a87",
          "sha256": "3868452a75c7a86c71f5a668e6361b58d7725685a39ecaec1e8777aa26071dbd",
          "sha1": "fa112adef63516055a7eb85bbfaf11dd4480f280",
          "md5": "7ef5c54c0a39439fdb369443fc2672f8"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.14"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.2.14.klib",
          "url": "toolkit-web-js-0.2.14.klib",
          "size": 714746,
          "sha512": "db0aba566054dd90cef251544793c9d109e6fe37893099559cda22b6588fc39991a440ef43482bd121a260e27de3975d0fc67f63b0b049fb2a22e64962436a87",
          "sha256": "3868452a75c7a86c71f5a668e6361b58d7725685a39ecaec1e8777aa26071dbd",
          "sha1": "fa112adef63516055a7eb85bbfaf11dd4480f280",
          "md5": "7ef5c54c0a39439fdb369443fc2672f8"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "toolkit-web-js-0.2.14-sources.jar",
          "url": "toolkit-web-js-0.2.14-sources.jar",
          "size": 302454,
          "sha512": "13375eb3f66fc0d54b4d87ba1e75d6b16db0c568f552f60f2d594885480eff0c4b97b47bc6d4af0ae02b6a369b74481f66ca3be5b4037a7c09e1bac5c543047f",
          "sha256": "9b78f22398b690e9332fd0531f1cef07325e33725ab63481ee33d9ced0060656",
          "sha1": "ac130475d2c34c547122dddd3cc24900c9d149f2",
          "md5": "501b532a20a7a831991aa49ea4a579d0"
        }
      ]
    }
  ]
}
