{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-web/0.2.4/toolkit-web-0.2.4.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-web",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.2.4.klib",
          "url": "toolkit-web-js-0.2.4.klib",
          "size": 634526,
          "sha512": "bd1c80804034a1506c34183621f4acb9ff12de836059151b5ab15322b49b8a86c3bf546a0a880413a38c72d570e694afaef16b299b4bdabca5957d549a828653",
          "sha256": "2f713e014b175829b33a848bcf120418e9687b916061c0702f431162c2bf92cf",
          "sha1": "7dee5d6ee5f8ac20b6f28087f2e4225e85208f49",
          "md5": "eddb36271317ccbd132067810fef6440"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.2.4.klib",
          "url": "toolkit-web-js-0.2.4.klib",
          "size": 634526,
          "sha512": "bd1c80804034a1506c34183621f4acb9ff12de836059151b5ab15322b49b8a86c3bf546a0a880413a38c72d570e694afaef16b299b4bdabca5957d549a828653",
          "sha256": "2f713e014b175829b33a848bcf120418e9687b916061c0702f431162c2bf92cf",
          "sha1": "7dee5d6ee5f8ac20b6f28087f2e4225e85208f49",
          "md5": "eddb36271317ccbd132067810fef6440"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "toolkit-web-js-0.2.4-sources.jar",
          "url": "toolkit-web-js-0.2.4-sources.jar",
          "size": 259535,
          "sha512": "35fa135c1ee73eb1b64fa80d9d4d48c0b412a10ea1e1cce91185158df172e31537ac119caf4339f929d8d62c92ba21b4eccedf8e227275ddb9fe1bf3e15ff527",
          "sha256": "bf3e2f64807256ff8005d1424b37c5a44fc90ab391359b193ed4849f98990f1c",
          "sha1": "a8bd60caebb187369b6b1c953b11af50ed1eb4ba",
          "md5": "11703048cad7028ed3d984f2488c5b79"
        }
      ]
    }
  ]
}
