{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-web/0.2.10/toolkit-web-0.2.10.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-web",
    "version": "0.2.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.2.10.klib",
          "url": "toolkit-web-js-0.2.10.klib",
          "size": 654750,
          "sha512": "e2f765a0797ef6cb78f3e02455eebdd2ed01dca0e3f70510c3661a62c0dc75fc5282c6bd3dce62d61895f517a765678a8d4a62d2212e739adb1a2c89b7179747",
          "sha256": "ea139bf6f989c2cfd23bb0ddfa182b0e7840d22fa0fff17c34a5c5adf584c792",
          "sha1": "5f5ca37fc7666a3510642d575f7ee713455927fc",
          "md5": "9398abbb85f0169367072f4a4fdd6e8f"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.2.10.klib",
          "url": "toolkit-web-js-0.2.10.klib",
          "size": 654750,
          "sha512": "e2f765a0797ef6cb78f3e02455eebdd2ed01dca0e3f70510c3661a62c0dc75fc5282c6bd3dce62d61895f517a765678a8d4a62d2212e739adb1a2c89b7179747",
          "sha256": "ea139bf6f989c2cfd23bb0ddfa182b0e7840d22fa0fff17c34a5c5adf584c792",
          "sha1": "5f5ca37fc7666a3510642d575f7ee713455927fc",
          "md5": "9398abbb85f0169367072f4a4fdd6e8f"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "toolkit-web-js-0.2.10-sources.jar",
          "url": "toolkit-web-js-0.2.10-sources.jar",
          "size": 274805,
          "sha512": "a5ff1eeae430abeff05b8100aa573f9b2babd66299cea91bf235c7318f11e860d59bf9a31010b097a6e11f8997a20d3dc49e4ce8735f9bf98a651359facc9c6e",
          "sha256": "63e10a8470e44a0dc19616e12e30c0309926c1601efc29667a209f8c53195952",
          "sha1": "d2683caa3f87cb16cc066460abef2436ac193184",
          "md5": "41f70464a71dba125e942c230a94926e"
        }
      ]
    }
  ]
}
