{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-store/0.2.38/lunula-store-0.2.38.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-store",
    "version": "0.2.38",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.38"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-store-iosSimulatorArm64Main-0.2.38.klib",
          "url": "lunula-store-iossimulatorarm64-0.2.38.klib",
          "size": 61161,
          "sha512": "7b2af0a8ec60f7888d0911f6a32a19fdc7fab09713a0401adb2be06ff53c524ec8ed8c46a180b88274a953f90340e41ba5a225bacb4c4a362ef894df83a347cc",
          "sha256": "0c2116b734c37d00ea93a87d1140d22c1d4fec9759e4d79c46bd2a6bf2bd904a",
          "sha1": "c3d2cf4a24f6ebe679d83903f78706abe36c6361",
          "md5": "988823480aa7326bcfb244fb74ab31b9"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "lunula-store-iossimulatorarm64-0.2.38-sources.jar",
          "url": "lunula-store-iossimulatorarm64-0.2.38-sources.jar",
          "size": 17799,
          "sha512": "941ee2cfd1707f8a76f3c1824125c2055744297f08bb17612cb1c93bf35f24c56d15120ea0755e067c3ad4b65e7e0c8b9e86f710e39b8a244a46db9865862944",
          "sha256": "1340350f441dac938c65411974ee54f86105d7589f22323628c4d16f915ab227",
          "sha1": "58d4749e0d9acac572d6d9bcc8e093672a54c91b",
          "md5": "1631e81f5a87a052b04bdc316ae2a38a"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.38"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-store-iossimulatorarm64-0.2.38-metadata.jar",
          "url": "lunula-store-iossimulatorarm64-0.2.38-metadata.jar",
          "size": 3829,
          "sha512": "36db2b952b11db022a52be17e141a5bab95116cdd8f895d5120773dd37cd61b428e3dc68bf5e00eb31cbbdd1a2768a79a74acfef5618fc56916a481419b710ef",
          "sha256": "2369bec13f609c6b4a96402a5187434c10a66bc395b48f8563b83e5df6b406f9",
          "sha1": "6c0e9bc5ff357af81a7d1104bd7a6281c31295d5",
          "md5": "04e2345f7a75d4b44a9efba8eebf9b49"
        }
      ]
    }
  ]
}
