{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-core/0.2.10/toolkit-core-0.2.10.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-core",
    "version": "0.2.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-iosSimulatorArm64Main-0.2.10.klib",
          "url": "toolkit-core-iossimulatorarm64-0.2.10.klib",
          "size": 108349,
          "sha512": "54ac11212df275c7be1fcc485d27f2516e71177acd860f21feaa2858f94bad3a47eab3c6782c98112edfb8c96d8fab50f8ab337413eb84e5ea9570abd71756c6",
          "sha256": "cc3a07461cdda53a2c97dcbbc585e0bfddd17931f052a6340fe1635a71698e44",
          "sha1": "0bef9ad662d7e7da9479dcc782662dc0896e2f87",
          "md5": "da4157d6939b5a1e6ccc2e2dff17e6c2"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "toolkit-core-iossimulatorarm64-0.2.10-sources.jar",
          "url": "toolkit-core-iossimulatorarm64-0.2.10-sources.jar",
          "size": 30345,
          "sha512": "22f9c3145e18a26326c51193042bac1536fcc9527ce5cd4327193cf9eca3c30dce5e98e7559d39d2905871b484d8bebcf95c8bd1804de42e79c1142e77a7ebfe",
          "sha256": "4af1eb0bab6321d19b0f11e07aa6b6d81d6744d2dea23cd24b532829c103588b",
          "sha1": "c158d1f3a2770dfdeab654609fb785fbd7a0f3b5",
          "md5": "3f2fa599501a08aedc0398f8235bfa01"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-iossimulatorarm64-0.2.10-metadata.jar",
          "url": "toolkit-core-iossimulatorarm64-0.2.10-metadata.jar",
          "size": 261,
          "sha512": "ddb17afc6f3d21b9c910cf3621efb0ebaaecd927d505626ea961ca28f6ebfb9e0ea295ceb3a8a9481dd77950843b1d1b76d2ef10e1e9c22a49359922cfff3764",
          "sha256": "4dbd3105543ab0abd17d9bf4046a2d25cfa5fb4f091ba8f4d9f656ceb86df4f9",
          "sha1": "addf5a2c04013ef332d378bfd788c03c568cde08",
          "md5": "f6fc7460f8f7c444cecb99d22eeecabe"
        }
      ]
    }
  ]
}
