{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-store/0.2.38/lunula-store-0.2.38.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-store",
    "version": "0.2.38",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.38"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-store-release.aar",
          "url": "lunula-store-android-0.2.38.aar",
          "size": 59542,
          "sha512": "746c00d74d452bfad1221722308b6563b346799351cdf86f7bb2465d3a985ab27c6b257caefb7e32478868ca3905547cd05b84d0db3ef867214d0318829560ee",
          "sha256": "406259bf09b03a7f3c1035eb80a1d5d43c93473f3b80c3d028c48ca4f643ab54",
          "sha1": "dc4be38ec07f36b4c8b75566fa8025faa51607be",
          "md5": "837fe41cdc10fb93ee1b1f57bd64a135"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.38"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "lunula-store-release.aar",
          "url": "lunula-store-android-0.2.38.aar",
          "size": 59542,
          "sha512": "746c00d74d452bfad1221722308b6563b346799351cdf86f7bb2465d3a985ab27c6b257caefb7e32478868ca3905547cd05b84d0db3ef867214d0318829560ee",
          "sha256": "406259bf09b03a7f3c1035eb80a1d5d43c93473f3b80c3d028c48ca4f643ab54",
          "sha1": "dc4be38ec07f36b4c8b75566fa8025faa51607be",
          "md5": "837fe41cdc10fb93ee1b1f57bd64a135"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "lunula-store-android-0.2.38-sources.jar",
          "url": "lunula-store-android-0.2.38-sources.jar",
          "size": 20049,
          "sha512": "3aa3f7585051ce52d0dc31329c30427726ff0113fb2b61411b9fd2aaa72b900d35e3d3bce8ce3562b1b53ae70b23e56ddc5a31910f275f84a7d20ed415726566",
          "sha256": "6179b6581b111639455fd451108529819b5a79e835339893d0a81c46e435d044",
          "sha1": "fa9250731f98ed7648e7daa5353fc71acdc84650",
          "md5": "be17f3435f579200c23686b3a9c857c6"
        }
      ]
    }
  ]
}
