{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-core/0.2.40/lunula-core-0.2.40.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-core",
    "version": "0.2.40",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-iosArm64Main-0.2.40.klib",
          "url": "lunula-core-iosarm64-0.2.40.klib",
          "size": 135352,
          "sha512": "6423bf2fa39588fdc638599e38a305d3671764f85088dcdabe64ef4b2618985b7cb1f0846da28dbd50713f8ebc413c180385fadd3c14aa46c244fa5c05a07814",
          "sha256": "e2935d6f33a1326cca983ff647620b52e1b026c9f6ebfff014311480718cf59b",
          "sha1": "861f5cbbf48e97df8e04ecb96eeafd5ebc588fdc",
          "md5": "1f623ed0261f898fb019c83445f33050"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "lunula-core-iosarm64-0.2.40-sources.jar",
          "url": "lunula-core-iosarm64-0.2.40-sources.jar",
          "size": 41135,
          "sha512": "6e60fb4c5223ab05b9e182d510a9f87b1131e5f3d3c57449674c858cc2569f6b09502fd7a7d3e78020a86cce88fe413a63eeaa9e477df90fe68fab78689646d6",
          "sha256": "830b7500fd2cbaa47abaedbf9b3b7b8eb9dd35bda1557a3df46bf50a2095206d",
          "sha1": "75835b5733c44641e7dd8794e1e24559c7540938",
          "md5": "ba748b1ee219f766e060d033fd6e0d4f"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-iosarm64-0.2.40-metadata.jar",
          "url": "lunula-core-iosarm64-0.2.40-metadata.jar",
          "size": 261,
          "sha512": "2d0f38149fe76d3de07de717672b7f8d5870e1682bbf08d7b0b46780c3c7db8db9697f2fd0b01685d95f5a5dc526065c462d622bd41d41b999d3a151282e9e8e",
          "sha256": "2ca7534916270e0dcf7f2da2f73f18565956882fc5f24161a0fd199c92301ab3",
          "sha1": "5fbda264dc66586b30496f7b55dadaf61b0b5812",
          "md5": "994227fd0e7fdc0dea2b3f3857f949b2"
        }
      ]
    }
  ]
}
