{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-store/0.2.38/lunula-store-0.2.38.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-store",
    "version": "0.2.38",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.38"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-store-js-0.2.38.klib",
          "url": "lunula-store-js-0.2.38.klib",
          "size": 54484,
          "sha512": "509fe158999b39e4bae6e6cb2496acd2238c77fdb97fd4d9f1563ff4f0cbc4a102570002245306e87abeda485e86f59e41ae93d99e1a68cee628d8f5d2571de4",
          "sha256": "9f3e11708009e5a89a0ad87ffd8602e998b24872048dbb7b386f88a8cac4d043",
          "sha1": "d5be4cbedb64a531fd847816e969963be1365200",
          "md5": "c14e71c4647dd2b1e2e000a1c5eb137b"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.38"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-store-js-0.2.38.klib",
          "url": "lunula-store-js-0.2.38.klib",
          "size": 54484,
          "sha512": "509fe158999b39e4bae6e6cb2496acd2238c77fdb97fd4d9f1563ff4f0cbc4a102570002245306e87abeda485e86f59e41ae93d99e1a68cee628d8f5d2571de4",
          "sha256": "9f3e11708009e5a89a0ad87ffd8602e998b24872048dbb7b386f88a8cac4d043",
          "sha1": "d5be4cbedb64a531fd847816e969963be1365200",
          "md5": "c14e71c4647dd2b1e2e000a1c5eb137b"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "lunula-store-js-0.2.38-sources.jar",
          "url": "lunula-store-js-0.2.38-sources.jar",
          "size": 17714,
          "sha512": "85ee649a5da75db899bba81239d4e6ea7d90e73298c9200575ea85c7eb239eeea76f66d3e1c40d0231430378fb35332000155252050b2ff9e9699cbbd9aeac31",
          "sha256": "524c7e2d8281ed5cf7386775d4b6bb0bb8d9280870f7df688d02fc64849f5ffb",
          "sha1": "6a5ffd796183579a8bc353bbee23fcdc905880c9",
          "md5": "37e5bd4fdf5158866352c48085034488"
        }
      ]
    }
  ]
}
