{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-web/0.2.7/toolkit-web-0.2.7.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-web",
    "version": "0.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.2.7.klib",
          "url": "toolkit-web-js-0.2.7.klib",
          "size": 640440,
          "sha512": "176d6ea7cd7901f4f47a977f9c12f5f681e009970fb11b3c951c254e782fed22ed079899571a0bdf2a1e3a3bfc152e9b36791fe32678dfcb4c2cbac2dbfd4a4e",
          "sha256": "5468fc5061d3a14b549c6804b4fc90b9b709d19fc324319808aead57ed435922",
          "sha1": "f6fb13f3f43f236ffc44eeea722797cf0bd3e39d",
          "md5": "2d3f37f764e0d000fa1a20e59b937871"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.2.7.klib",
          "url": "toolkit-web-js-0.2.7.klib",
          "size": 640440,
          "sha512": "176d6ea7cd7901f4f47a977f9c12f5f681e009970fb11b3c951c254e782fed22ed079899571a0bdf2a1e3a3bfc152e9b36791fe32678dfcb4c2cbac2dbfd4a4e",
          "sha256": "5468fc5061d3a14b549c6804b4fc90b9b709d19fc324319808aead57ed435922",
          "sha1": "f6fb13f3f43f236ffc44eeea722797cf0bd3e39d",
          "md5": "2d3f37f764e0d000fa1a20e59b937871"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "toolkit-web-js-0.2.7-sources.jar",
          "url": "toolkit-web-js-0.2.7-sources.jar",
          "size": 264804,
          "sha512": "1caf5605ddafa71581bc45af5f607048cb2750903a99059613f709511bbb3ccbe5d71d30c4b593e813efb36edd479ed59784da02809e41452575d685528b2a15",
          "sha256": "fd8f87461137ab4d797f897e755ba746d3da38de141302940e2e0a89ce13f504",
          "sha1": "e8db106f8f2a567f1319304af64e6184ed5896f9",
          "md5": "bd0e1d04866119213c6511b60fe1b3df"
        }
      ]
    }
  ]
}
