{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-core/0.2.4/toolkit-core-0.2.4.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-core",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-iosSimulatorArm64Main-0.2.4.klib",
          "url": "toolkit-core-iossimulatorarm64-0.2.4.klib",
          "size": 108374,
          "sha512": "3a2a73f74e707bae062089677f89035c5b1eab03da8bd50d6db94fe5c12b7f3ed578b6dc59bc68f76a83649b9179e296c16cfff73bb463e8f109f0251be7fbe7",
          "sha256": "c5692112bca30bdb5cf6defaf921f94e2f31fe1b02b25cf050a166295adfffe1",
          "sha1": "c1c602ab431856d421a132928bd39ecacc2a1652",
          "md5": "99a7bc3fdcc64084c874b27d0edfa11f"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "toolkit-core-iossimulatorarm64-0.2.4-sources.jar",
          "url": "toolkit-core-iossimulatorarm64-0.2.4-sources.jar",
          "size": 30354,
          "sha512": "e0ac19659bc0ce0fdbee13ef1ca1a760cd564e543681d7dc61eac1d4c4df4b87d00add402f5ff12e7766b1ed40eababd9090d985593f10b5b6921d49268ed251",
          "sha256": "925b11edd673510395469156bd0548e6c0f4234237727d4d48935e758c6ce73c",
          "sha1": "1c10482b7c393cbf36af436629229429346b06ea",
          "md5": "5025f4d132c82eee54ee752e9c367378"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-iossimulatorarm64-0.2.4-metadata.jar",
          "url": "toolkit-core-iossimulatorarm64-0.2.4-metadata.jar",
          "size": 261,
          "sha512": "e5c42bf88414e798bc1d1566d3122579bd77683a6e67b93f36b4be0d1f8c1f88ed37b177d5bc2d32ca5b13a5054276cee4bad17c1ab102429ea4b299dd928f02",
          "sha256": "d7ae74c3aa91dbc4fc3fe0226ca48128bbb38dc7f29f399ccdc36d5cf565120b",
          "sha1": "bf302a7bea211de6ad19f67b052472bda0d177d0",
          "md5": "3d1c161f8fbb2461b38ff142e2af1573"
        }
      ]
    }
  ]
}
