{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-web/0.2.37/toolkit-web-0.2.37.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-web",
    "version": "0.2.37",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.37"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.2.37.klib",
          "url": "toolkit-web-js-0.2.37.klib",
          "size": 785667,
          "sha512": "a4be9c08190a79d72b65dfad082dc1cd1b4f62477dadd07547ae851263262e1e828bea19f9fe091e262e7fde4ec13b5beb8c4e0fbdfb4568d91b326ac6452a2f",
          "sha256": "0c9794b740d9f2beb5c97fe9b8c8d44ef761df214a3b27cfebeb40122f2470e5",
          "sha1": "aa1eb1fb4d6c10bea0f69bfb07da143a1e2320f2",
          "md5": "514d56a4bcac843a432672e54a04b312"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.37"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.2.37.klib",
          "url": "toolkit-web-js-0.2.37.klib",
          "size": 785667,
          "sha512": "a4be9c08190a79d72b65dfad082dc1cd1b4f62477dadd07547ae851263262e1e828bea19f9fe091e262e7fde4ec13b5beb8c4e0fbdfb4568d91b326ac6452a2f",
          "sha256": "0c9794b740d9f2beb5c97fe9b8c8d44ef761df214a3b27cfebeb40122f2470e5",
          "sha1": "aa1eb1fb4d6c10bea0f69bfb07da143a1e2320f2",
          "md5": "514d56a4bcac843a432672e54a04b312"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "toolkit-web-js-0.2.37-sources.jar",
          "url": "toolkit-web-js-0.2.37-sources.jar",
          "size": 339544,
          "sha512": "77fb998c23ce254fa5f2a82c46cc3da3bba829a5a059039ee51800f2da2d4ccc35022cfb30ad2bb1d228952a7e2c1ee7572a87f00837b001e9c2bc8de602e8a9",
          "sha256": "015ab7c31316821c941b8d071c2e5d09a835737553ee7ac29f2f17fb9472c10a",
          "sha1": "ec1912e54eedc0e9f5cc6242cfecfecfdc4dfa54",
          "md5": "1ea64121d9d1b2b03e15f5287a4dc190"
        }
      ]
    }
  ]
}
