{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-web/0.2.41/lunula-web-0.2.41.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-web",
    "version": "0.2.41",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.41"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-web-js-0.2.41.klib",
          "url": "lunula-web-js-0.2.41.klib",
          "size": 798847,
          "sha512": "bacef59e973dfd8f4af2bb1418f9ff94b00b52361d0df96b485d9908cd53224fb66232c7cffbf91ccc65e1337313756e50c12a3f2ad6799a5c4a42ea5e14decc",
          "sha256": "aa00659475bf6ddfdaaf47a0fbe85249ac61f563ae167df1c0bbcd1b36c0d67d",
          "sha1": "bed3088ffd0b0b2d2e50c2870da1cc2ae29e366f",
          "md5": "a4f86583a60fcc0381e411b8535ff2b2"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.41"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-web-js-0.2.41.klib",
          "url": "lunula-web-js-0.2.41.klib",
          "size": 798847,
          "sha512": "bacef59e973dfd8f4af2bb1418f9ff94b00b52361d0df96b485d9908cd53224fb66232c7cffbf91ccc65e1337313756e50c12a3f2ad6799a5c4a42ea5e14decc",
          "sha256": "aa00659475bf6ddfdaaf47a0fbe85249ac61f563ae167df1c0bbcd1b36c0d67d",
          "sha1": "bed3088ffd0b0b2d2e50c2870da1cc2ae29e366f",
          "md5": "a4f86583a60fcc0381e411b8535ff2b2"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "lunula-web-js-0.2.41-sources.jar",
          "url": "lunula-web-js-0.2.41-sources.jar",
          "size": 348892,
          "sha512": "9b33f8067bd3283a2508805b69e99932652e3548e0081e845cfb75efbd26520b48c80d1fb7a6c88303afb96f2ff5d24e05a5eff0069c2eb97d8b80706136c118",
          "sha256": "57684dc0d681359eff2ef00ca6dad9be0d475ed06fd7f429fff2846c83cdd3b3",
          "sha1": "5e8a352975d045af918a5d8eb6e30874b44e930b",
          "md5": "d6c60c61686a067d9c7923d9b9e331d4"
        }
      ]
    }
  ]
}
