{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-web/0.2.2/toolkit-web-0.2.2.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-web",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.2.2.klib",
          "url": "toolkit-web-js-0.2.2.klib",
          "size": 632406,
          "sha512": "0bc8020f625fb1e26af31f0506a8f4b0290c2b129001fabdd06da0f2a160c74d8df0206bd0e4a50f41f3db7922ad0c42cb9883dd7e546247b038bc4e536e1187",
          "sha256": "7c75628caed5bf89474278758bfa89b6417e20e8b08ee48dfecb494f28e265f6",
          "sha1": "16bb696999d777d4bf7ac4a6b2aa2ab65971ec2d",
          "md5": "1b3d45f7da7ec229edb1bc7bf4a19945"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.2.2.klib",
          "url": "toolkit-web-js-0.2.2.klib",
          "size": 632406,
          "sha512": "0bc8020f625fb1e26af31f0506a8f4b0290c2b129001fabdd06da0f2a160c74d8df0206bd0e4a50f41f3db7922ad0c42cb9883dd7e546247b038bc4e536e1187",
          "sha256": "7c75628caed5bf89474278758bfa89b6417e20e8b08ee48dfecb494f28e265f6",
          "sha1": "16bb696999d777d4bf7ac4a6b2aa2ab65971ec2d",
          "md5": "1b3d45f7da7ec229edb1bc7bf4a19945"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "toolkit-web-js-0.2.2-sources.jar",
          "url": "toolkit-web-js-0.2.2-sources.jar",
          "size": 259148,
          "sha512": "11f4f7a8b0ab2aba9116ef0435edc0be0ef0b2303c50879207a75ae30585e6378b0cdbc260840114b92b1717f2cb4b5f9cafe3c2807a8da6442010be13022d7c",
          "sha256": "597c6eff284d846e4149c2b3055ffc50a904d31766108f0ffea740199b9b42e5",
          "sha1": "21098faf3c9104d766fa069a176fe469630dceb2",
          "md5": "732f4b5862890296a474b38c9ed0ad78"
        }
      ]
    }
  ]
}
