{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-web/0.2.11/toolkit-web-0.2.11.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-web",
    "version": "0.2.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.2.11.klib",
          "url": "toolkit-web-js-0.2.11.klib",
          "size": 708379,
          "sha512": "c6047660aaec7625be5199e0ca31d9838f9c0cb82227d243daa64bbf98318da999feaec8d07ef47847f98acfb2793a9847418822e1dd5bc679a38c3f18143a60",
          "sha256": "3aa532c039dac897c50598fd9a0a5c6a873adcebafefd25eab110ab68eeca425",
          "sha1": "0890233091c3db1de82f8157a33258c970dce8bf",
          "md5": "12e25cdb55456b2b373cadc3b9cf07bc"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.2.11.klib",
          "url": "toolkit-web-js-0.2.11.klib",
          "size": 708379,
          "sha512": "c6047660aaec7625be5199e0ca31d9838f9c0cb82227d243daa64bbf98318da999feaec8d07ef47847f98acfb2793a9847418822e1dd5bc679a38c3f18143a60",
          "sha256": "3aa532c039dac897c50598fd9a0a5c6a873adcebafefd25eab110ab68eeca425",
          "sha1": "0890233091c3db1de82f8157a33258c970dce8bf",
          "md5": "12e25cdb55456b2b373cadc3b9cf07bc"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "toolkit-web-js-0.2.11-sources.jar",
          "url": "toolkit-web-js-0.2.11-sources.jar",
          "size": 298462,
          "sha512": "1c5865fc27fe70035c01307207fe01e9b33da41b53e820cb774b6eac3ae9956f5247006510b56f0cd4dd833fbfff2e8896d2cd8e3fb8af5a5dba1cc91d764f10",
          "sha256": "4a041848ec228e9614604b49b452535ff6c43a958cfc0f45eb1733c43372951d",
          "sha1": "8f400c5acc3c5b82103af9238beba9f1e57b288b",
          "md5": "bee79d8f8cdb4354f58b0361bfac8002"
        }
      ]
    }
  ]
}
