{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-core/0.2.28/toolkit-core-0.2.28.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-core",
    "version": "0.2.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-js-0.2.28.klib",
          "url": "toolkit-core-js-0.2.28.klib",
          "size": 118112,
          "sha512": "e0eac57b707f1fe8b701915c5ccfd5ad3cfa49247c981b3ce9720673dc39e45af23e9d6f3f7247815b25e68131d2bd323835a1f0b47c37791e29ddcfba61d8bc",
          "sha256": "fe7904aa5716a31420bf53157f2330865de88dddfa562de7c4a967870be79ee7",
          "sha1": "0cbfd725ee6678dc8c304ff129ee1485001db5fd",
          "md5": "ab7039e94b3d39540b916ebf1aeab1d6"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-js-0.2.28.klib",
          "url": "toolkit-core-js-0.2.28.klib",
          "size": 118112,
          "sha512": "e0eac57b707f1fe8b701915c5ccfd5ad3cfa49247c981b3ce9720673dc39e45af23e9d6f3f7247815b25e68131d2bd323835a1f0b47c37791e29ddcfba61d8bc",
          "sha256": "fe7904aa5716a31420bf53157f2330865de88dddfa562de7c4a967870be79ee7",
          "sha1": "0cbfd725ee6678dc8c304ff129ee1485001db5fd",
          "md5": "ab7039e94b3d39540b916ebf1aeab1d6"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "toolkit-core-js-0.2.28-sources.jar",
          "url": "toolkit-core-js-0.2.28-sources.jar",
          "size": 40943,
          "sha512": "a58b0c258e0248ff7b912cd7250cd891a163034b541285ba2756ee7c47705b643bd4318dd925461902780c9af80054762c153d72e4f6f48467e177a33bbcd5d1",
          "sha256": "a42b5b2582cc1703c3503343f755af47e3d8107921cffbe9ac66ab9963ebc92a",
          "sha1": "09cbdcc822404f6e619611fd95f0584747a74fd6",
          "md5": "873be5bfaa239c9a77e72bb7b01f70e3"
        }
      ]
    }
  ]
}
