{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-core/0.2.38/lunula-core-0.2.38.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-core",
    "version": "0.2.38",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-js-0.2.38.klib",
          "url": "lunula-core-js-0.2.38.klib",
          "size": 118065,
          "sha512": "7c840121f84caf32351f95ffaefc6f77b25093423a2ec77328f6193a3304394dec34c871b46785acab89a86356c5a8db789f19eb6e1740e27d19c6bbc134c9a6",
          "sha256": "48d0ec307fbf2b0122c3b4469c61f4a6c8cb25660bca93dc85cccf4a2846ba84",
          "sha1": "cb33846e43763d5feeea61e4a1485037d58b6f74",
          "md5": "175253aa696d6ae04b5f1baecc590b6e"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-js-0.2.38.klib",
          "url": "lunula-core-js-0.2.38.klib",
          "size": 118065,
          "sha512": "7c840121f84caf32351f95ffaefc6f77b25093423a2ec77328f6193a3304394dec34c871b46785acab89a86356c5a8db789f19eb6e1740e27d19c6bbc134c9a6",
          "sha256": "48d0ec307fbf2b0122c3b4469c61f4a6c8cb25660bca93dc85cccf4a2846ba84",
          "sha1": "cb33846e43763d5feeea61e4a1485037d58b6f74",
          "md5": "175253aa696d6ae04b5f1baecc590b6e"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "lunula-core-js-0.2.38-sources.jar",
          "url": "lunula-core-js-0.2.38-sources.jar",
          "size": 41135,
          "sha512": "6e60fb4c5223ab05b9e182d510a9f87b1131e5f3d3c57449674c858cc2569f6b09502fd7a7d3e78020a86cce88fe413a63eeaa9e477df90fe68fab78689646d6",
          "sha256": "830b7500fd2cbaa47abaedbf9b3b7b8eb9dd35bda1557a3df46bf50a2095206d",
          "sha1": "75835b5733c44641e7dd8794e1e24559c7540938",
          "md5": "ba748b1ee219f766e060d033fd6e0d4f"
        }
      ]
    }
  ]
}
