{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-web/0.2.17/toolkit-web-0.2.17.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-web",
    "version": "0.2.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.17"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.2.17.klib",
          "url": "toolkit-web-js-0.2.17.klib",
          "size": 718343,
          "sha512": "4760ad5e710d38aacf191ec6ad64dffc16e024a9642dda1359fa511a59ff6ea89e52507e6c03c24fecdfbe7af1af072cc122fe5c6dfb039a4f147762ec97e796",
          "sha256": "ed0e0e01a2b213f5394c4b4206404bc0a4473e199ac7338b073219204ff0f999",
          "sha1": "0b4ed1c585c558de072af154110fd02c0708fded",
          "md5": "fc0b6f0ecfceea81cdce87c41c967c5c"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.17"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.2.17.klib",
          "url": "toolkit-web-js-0.2.17.klib",
          "size": 718343,
          "sha512": "4760ad5e710d38aacf191ec6ad64dffc16e024a9642dda1359fa511a59ff6ea89e52507e6c03c24fecdfbe7af1af072cc122fe5c6dfb039a4f147762ec97e796",
          "sha256": "ed0e0e01a2b213f5394c4b4206404bc0a4473e199ac7338b073219204ff0f999",
          "sha1": "0b4ed1c585c558de072af154110fd02c0708fded",
          "md5": "fc0b6f0ecfceea81cdce87c41c967c5c"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "toolkit-web-js-0.2.17-sources.jar",
          "url": "toolkit-web-js-0.2.17-sources.jar",
          "size": 304306,
          "sha512": "63c31ee85892e47d7893413264372fc8dcd7468759650d84fb257626dfdb9fbe9ae056409ba411bedf0133fa777dbce3cf39fe2fbc4af634e8337aaa9a625c2d",
          "sha256": "1a3b94ac0dd9f14346f1f2569073044a2f24d5ea65da79e50750183394aec51d",
          "sha1": "69bed1a8964a2dde6fb948319ad0bbce11a5feaf",
          "md5": "958ca9757f7ad8d908c887d35a724909"
        }
      ]
    }
  ]
}
