{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-store/0.2.7/toolkit-store-0.2.7.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-store",
    "version": "0.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-iosSimulatorArm64Main-0.2.7.klib",
          "url": "toolkit-store-iossimulatorarm64-0.2.7.klib",
          "size": 44739,
          "sha512": "9e458fc98f2d0caf1d3fd1284ef88a2ef4de78c360ad15a2225abf9a2229e3fb9b16601437a85e45109b58b526318d3e52c5d80e464155d68ddf1c16e7f4295a",
          "sha256": "68603acdc3f9860333c72bfa7623a3819ae52981fd1f82783903d667b6e4d271",
          "sha1": "fee1cc54296a0b22d5102ab17b72fce080ca5b78",
          "md5": "2e8ed021a2b3d827d016b1f599aacf39"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "toolkit-store-iossimulatorarm64-0.2.7-sources.jar",
          "url": "toolkit-store-iossimulatorarm64-0.2.7-sources.jar",
          "size": 13564,
          "sha512": "1e8d4691ecbbcf05087ef4e07a393a02c990fc1461c8f57f7bf7ca8c7c78d080505b35de1b3391cd948c7b9f5dd868eb78154fdfc371850ef784e967fd53efb6",
          "sha256": "8ee9c2fd5d255a51d8274892032028292ee844f5f5425729af2784f75991f724",
          "sha1": "b116f57e4a99c0ebf46eb20472c563bd743251ca",
          "md5": "b9fc5333cf3de2c670375e9256660200"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-iossimulatorarm64-0.2.7-metadata.jar",
          "url": "toolkit-store-iossimulatorarm64-0.2.7-metadata.jar",
          "size": 3865,
          "sha512": "61713f2c2b495fe5dff3464906abd87b941927424fb60e1eae33761ca311aea714739ad67cca3114b9adcea642f6f29a87f43c741808f9396a432c9f682e2016",
          "sha256": "beb440f9882d71b7dc95f418cbf0696baa35d652cc1005613d28791203d31f78",
          "sha1": "5db9780a246448ee3099519956c808d4a05e171f",
          "md5": "82ae9243a9fb9dcb2160b8ea32268c51"
        }
      ]
    }
  ]
}
