{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-web/0.2.38/lunula-web-0.2.38.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-web",
    "version": "0.2.38",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.38"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-web-js-0.2.38.klib",
          "url": "lunula-web-js-0.2.38.klib",
          "size": 788646,
          "sha512": "ad4a31840b1ef22ab97520c41cf67afa23743f910f2a95029f5d73f00baf9abd6fcbcc7d21e5b4d41296845206f998697be0bf4cca28ff9662280e551be30343",
          "sha256": "16cfe73361943617d5e4583d6b7fd4f865d7e0025c9ac6f5b4dfaf27a7bf4680",
          "sha1": "8fd15d5592387663c3d0617f3a229cd6518a3993",
          "md5": "ff7548b7b61d1b300558edb0a65cfe5d"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.38"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-web-js-0.2.38.klib",
          "url": "lunula-web-js-0.2.38.klib",
          "size": 788646,
          "sha512": "ad4a31840b1ef22ab97520c41cf67afa23743f910f2a95029f5d73f00baf9abd6fcbcc7d21e5b4d41296845206f998697be0bf4cca28ff9662280e551be30343",
          "sha256": "16cfe73361943617d5e4583d6b7fd4f865d7e0025c9ac6f5b4dfaf27a7bf4680",
          "sha1": "8fd15d5592387663c3d0617f3a229cd6518a3993",
          "md5": "ff7548b7b61d1b300558edb0a65cfe5d"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "lunula-web-js-0.2.38-sources.jar",
          "url": "lunula-web-js-0.2.38-sources.jar",
          "size": 341231,
          "sha512": "8601cb74522fdca5cf3aa3aa1a4b811483f5d89f890e4ae95520fda9ab3fdd5bb7b19f8ae684d0de746c67f04f040fed639ee1955f5f8cc8291d85cde2e6f96f",
          "sha256": "d0daad2564d34d0a64312ce8d83c8062791892a49f824c05dad8114707b7c175",
          "sha1": "66949080fb7b49f3921a423f426339cd01834810",
          "md5": "4d32e2de4017450cc2cbe84f97abaf20"
        }
      ]
    }
  ]
}
