{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-store/0.2.21/toolkit-store-0.2.21.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-store",
    "version": "0.2.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-iosArm64Main-0.2.21.klib",
          "url": "toolkit-store-iosarm64-0.2.21.klib",
          "size": 44811,
          "sha512": "0934981b7b477006da96473890f814bc92968b722d8b58e6fe0db8108fcc1bacab498f6e440916c09c303ef5f8c28fb08fa9367122a977fd785b74fba3bf1670",
          "sha256": "9ed49d06956147bf40ce2b684b043dc2aa460f572f000a7f04f56983a5c11171",
          "sha1": "636bf16e8b871a83080ef6e280abd8e38707eb73",
          "md5": "e96e0ab874bd234f1e2e4be64517b427"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "toolkit-store-iosarm64-0.2.21-sources.jar",
          "url": "toolkit-store-iosarm64-0.2.21-sources.jar",
          "size": 13757,
          "sha512": "787276d15fa9af841b1fa66b73895da3875289a6a037c7e408725edef7c3f80b49be1b569ec2943ca309347390c219c29b3103b47c68491eeae47ccb03499ced",
          "sha256": "cd806bfef522f3138bab592e1c385d662e3bc90dbc34423a40f17163776cee88",
          "sha1": "bbbfcef44773ae04d02753d4e48012260da71a78",
          "md5": "e37a51a7ee22ecb62ea45dcb1fb8caf9"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-iosarm64-0.2.21-metadata.jar",
          "url": "toolkit-store-iosarm64-0.2.21-metadata.jar",
          "size": 3865,
          "sha512": "a3abc3173ec435aafc3a88b8511c53b0a94896b373407a220a69576113f2b698c167830dce959e83a28fc14da2e3440408d6ef5270356a81ee70fe730efd76ee",
          "sha256": "dda6716be6b27c39b7d10634cfd58dcc248a8b16426471caa0ddb97135e3c8f0",
          "sha1": "d188d4f33599d1bb104ce65733248fedcd2241c2",
          "md5": "31aedc3f29f27c67ba9b839e514e1dfd"
        }
      ]
    }
  ]
}
