{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-core/0.2.28/toolkit-core-0.2.28.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-core",
    "version": "0.2.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-jvm-0.2.28.jar",
          "url": "toolkit-core-jvm-0.2.28.jar",
          "size": 96775,
          "sha512": "0e6b90f4557373f8188dafbaba504374ed267abe0a9a14eaa89406e30795375970cf31dd74d3cf494ed9104a4419850cf13ce83d92a0f7512dc4730a4f139b7c",
          "sha256": "2cfc3056785991ee23f3b507f4b3519a666e3d248e78f2e795d6101f011f0679",
          "sha1": "53ab4b25345f9b9f1db92b38a045657b0298691d",
          "md5": "8622126ce2186ebefac2bf0404f68782"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-jvm-0.2.28.jar",
          "url": "toolkit-core-jvm-0.2.28.jar",
          "size": 96775,
          "sha512": "0e6b90f4557373f8188dafbaba504374ed267abe0a9a14eaa89406e30795375970cf31dd74d3cf494ed9104a4419850cf13ce83d92a0f7512dc4730a4f139b7c",
          "sha256": "2cfc3056785991ee23f3b507f4b3519a666e3d248e78f2e795d6101f011f0679",
          "sha1": "53ab4b25345f9b9f1db92b38a045657b0298691d",
          "md5": "8622126ce2186ebefac2bf0404f68782"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "toolkit-core-jvm-0.2.28-sources.jar",
          "url": "toolkit-core-jvm-0.2.28-sources.jar",
          "size": 40943,
          "sha512": "a58b0c258e0248ff7b912cd7250cd891a163034b541285ba2756ee7c47705b643bd4318dd925461902780c9af80054762c153d72e4f6f48467e177a33bbcd5d1",
          "sha256": "a42b5b2582cc1703c3503343f755af47e3d8107921cffbe9ac66ab9963ebc92a",
          "sha1": "09cbdcc822404f6e619611fd95f0584747a74fd6",
          "md5": "873be5bfaa239c9a77e72bb7b01f70e3"
        }
      ]
    }
  ]
}
